// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/media.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'movie_data/movie_data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMediaInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 890826887;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_fluster_media_center',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<MediaData> crateApiMediaGetMedia({required PlatformInt64 mediaId});

  Future<List<PersonData>> crateApiMediaGetMediaCast({
    required PlatformInt64 mediaId,
  });

  Future<List<PersonData>> crateApiMediaGetMediaCrew({
    required PlatformInt64 mediaId,
  });

  Future<List<MovieSnapshot>> crateApiMediaGetMediaSnapshots({
    required String mediaType,
  });

  Future<void> crateApiMediaInitApp();

  Future<void> crateApiMediaOpenVideo({required String path});

  Future<String> crateApiMediaStart({
    required String path,
    required String username,
    required String password,
    required String token,
  });

  Future<void> crateApiMediaTempoMountSmb();

  Future<void> crateApiMediaTempoUnmountSmb();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<MediaData> crateApiMediaGetMedia({required PlatformInt64 mediaId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(mediaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaGetMediaConstMeta,
        argValues: [mediaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaGetMediaConstMeta =>
      const TaskConstMeta(debugName: "get_media", argNames: ["mediaId"]);

  @override
  Future<List<PersonData>> crateApiMediaGetMediaCast({
    required PlatformInt64 mediaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(mediaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_person_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaGetMediaCastConstMeta,
        argValues: [mediaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaGetMediaCastConstMeta =>
      const TaskConstMeta(debugName: "get_media_cast", argNames: ["mediaId"]);

  @override
  Future<List<PersonData>> crateApiMediaGetMediaCrew({
    required PlatformInt64 mediaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(mediaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_person_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaGetMediaCrewConstMeta,
        argValues: [mediaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaGetMediaCrewConstMeta =>
      const TaskConstMeta(debugName: "get_media_crew", argNames: ["mediaId"]);

  @override
  Future<List<MovieSnapshot>> crateApiMediaGetMediaSnapshots({
    required String mediaType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mediaType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_movie_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaGetMediaSnapshotsConstMeta,
        argValues: [mediaType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaGetMediaSnapshotsConstMeta =>
      const TaskConstMeta(
        debugName: "get_media_snapshots",
        argNames: ["mediaType"],
      );

  @override
  Future<void> crateApiMediaInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMediaInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiMediaOpenVideo({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaOpenVideoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaOpenVideoConstMeta =>
      const TaskConstMeta(debugName: "open_video", argNames: ["path"]);

  @override
  Future<String> crateApiMediaStart({
    required String path,
    required String username,
    required String password,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMediaStartConstMeta,
        argValues: [path, username, password, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaStartConstMeta => const TaskConstMeta(
    debugName: "start",
    argNames: ["path", "username", "password", "token"],
  );

  @override
  Future<void> crateApiMediaTempoMountSmb() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaTempoMountSmbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaTempoMountSmbConstMeta =>
      const TaskConstMeta(debugName: "tempo_mount_smb", argNames: []);

  @override
  Future<void> crateApiMediaTempoUnmountSmb() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMediaTempoUnmountSmbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaTempoUnmountSmbConstMeta =>
      const TaskConstMeta(debugName: "tempo_unmount_smb", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<MovieSnapshot> dco_decode_list_movie_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_movie_snapshot).toList();
  }

  @protected
  List<PersonData> dco_decode_list_person_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_person_data).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaData dco_decode_media_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return MediaData(
      id: dco_decode_i_64(arr[0]),
      filePath: dco_decode_String(arr[1]),
      fileOptionalInfo: dco_decode_String(arr[2]),
      originalTitle: dco_decode_String(arr[3]),
      title: dco_decode_String(arr[4]),
      rating: dco_decode_f_32(arr[5]),
      releaseDate: dco_decode_String(arr[6]),
      summary: dco_decode_String(arr[7]),
      posterLarge: dco_decode_String(arr[8]),
      backdrop: dco_decode_String(arr[9]),
    );
  }

  @protected
  MovieSnapshot dco_decode_movie_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MovieSnapshot(
      id: dco_decode_i_64(arr[0]),
      filePath: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      rating: dco_decode_f_32(arr[3]),
      releaseDate: dco_decode_String(arr[4]),
      posterSnapshot: dco_decode_String(arr[5]),
    );
  }

  @protected
  PersonData dco_decode_person_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PersonData(
      tmdbId: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      character: dco_decode_String(arr[2]),
      jobName: dco_decode_String(arr[3]),
      picturePath: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<MovieSnapshot> sse_decode_list_movie_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MovieSnapshot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_movie_snapshot(deserializer));
    }
    return ans_;
  }

  @protected
  List<PersonData> sse_decode_list_person_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PersonData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_person_data(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaData sse_decode_media_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_fileOptionalInfo = sse_decode_String(deserializer);
    var var_originalTitle = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_rating = sse_decode_f_32(deserializer);
    var var_releaseDate = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_posterLarge = sse_decode_String(deserializer);
    var var_backdrop = sse_decode_String(deserializer);
    return MediaData(
      id: var_id,
      filePath: var_filePath,
      fileOptionalInfo: var_fileOptionalInfo,
      originalTitle: var_originalTitle,
      title: var_title,
      rating: var_rating,
      releaseDate: var_releaseDate,
      summary: var_summary,
      posterLarge: var_posterLarge,
      backdrop: var_backdrop,
    );
  }

  @protected
  MovieSnapshot sse_decode_movie_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_rating = sse_decode_f_32(deserializer);
    var var_releaseDate = sse_decode_String(deserializer);
    var var_posterSnapshot = sse_decode_String(deserializer);
    return MovieSnapshot(
      id: var_id,
      filePath: var_filePath,
      title: var_title,
      rating: var_rating,
      releaseDate: var_releaseDate,
      posterSnapshot: var_posterSnapshot,
    );
  }

  @protected
  PersonData sse_decode_person_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tmdbId = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_character = sse_decode_String(deserializer);
    var var_jobName = sse_decode_String(deserializer);
    var var_picturePath = sse_decode_String(deserializer);
    return PersonData(
      tmdbId: var_tmdbId,
      name: var_name,
      character: var_character,
      jobName: var_jobName,
      picturePath: var_picturePath,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_movie_snapshot(
    List<MovieSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_movie_snapshot(item, serializer);
    }
  }

  @protected
  void sse_encode_list_person_data(
    List<PersonData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_person_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_data(MediaData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_String(self.fileOptionalInfo, serializer);
    sse_encode_String(self.originalTitle, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_f_32(self.rating, serializer);
    sse_encode_String(self.releaseDate, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_String(self.posterLarge, serializer);
    sse_encode_String(self.backdrop, serializer);
  }

  @protected
  void sse_encode_movie_snapshot(MovieSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_f_32(self.rating, serializer);
    sse_encode_String(self.releaseDate, serializer);
    sse_encode_String(self.posterSnapshot, serializer);
  }

  @protected
  void sse_encode_person_data(PersonData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.tmdbId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.character, serializer);
    sse_encode_String(self.jobName, serializer);
    sse_encode_String(self.picturePath, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
