// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MovieSnapshot {
  final PlatformInt64 tmdbId;
  final String filePath;
  final String title;
  final double rating;
  final String releaseDate;
  final String posterSnapshot;

  const MovieSnapshot({
    required this.tmdbId,
    required this.filePath,
    required this.title,
    required this.rating,
    required this.releaseDate,
    required this.posterSnapshot,
  });

  @override
  int get hashCode =>
      tmdbId.hashCode ^
      filePath.hashCode ^
      title.hashCode ^
      rating.hashCode ^
      releaseDate.hashCode ^
      posterSnapshot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MovieSnapshot &&
          runtimeType == other.runtimeType &&
          tmdbId == other.tmdbId &&
          filePath == other.filePath &&
          title == other.title &&
          rating == other.rating &&
          releaseDate == other.releaseDate &&
          posterSnapshot == other.posterSnapshot;
}
