// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MediaData {
  final PlatformInt64 id;
  final String filePath;
  final String fileOptionalInfo;
  final String originalTitle;
  final String title;
  final double rating;
  final String releaseDate;
  final String summary;
  final String poster;
  final String backdrop;

  const MediaData({
    required this.id,
    required this.filePath,
    required this.fileOptionalInfo,
    required this.originalTitle,
    required this.title,
    required this.rating,
    required this.releaseDate,
    required this.summary,
    required this.poster,
    required this.backdrop,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      filePath.hashCode ^
      fileOptionalInfo.hashCode ^
      originalTitle.hashCode ^
      title.hashCode ^
      rating.hashCode ^
      releaseDate.hashCode ^
      summary.hashCode ^
      poster.hashCode ^
      backdrop.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          filePath == other.filePath &&
          fileOptionalInfo == other.fileOptionalInfo &&
          originalTitle == other.originalTitle &&
          title == other.title &&
          rating == other.rating &&
          releaseDate == other.releaseDate &&
          summary == other.summary &&
          poster == other.poster &&
          backdrop == other.backdrop;
}

class MovieSnapshot {
  final PlatformInt64 id;
  final String filePath;
  final String title;
  final double rating;
  final String releaseDate;
  final String poster;

  const MovieSnapshot({
    required this.id,
    required this.filePath,
    required this.title,
    required this.rating,
    required this.releaseDate,
    required this.poster,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      filePath.hashCode ^
      title.hashCode ^
      rating.hashCode ^
      releaseDate.hashCode ^
      poster.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MovieSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          filePath == other.filePath &&
          title == other.title &&
          rating == other.rating &&
          releaseDate == other.releaseDate &&
          poster == other.poster;
}

class PersonData {
  final PlatformInt64 tmdbId;
  final String name;
  final String summary;
  final String? picturePath;

  const PersonData({
    required this.tmdbId,
    required this.name,
    required this.summary,
    this.picturePath,
  });

  @override
  int get hashCode =>
      tmdbId.hashCode ^ name.hashCode ^ summary.hashCode ^ picturePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonData &&
          runtimeType == other.runtimeType &&
          tmdbId == other.tmdbId &&
          name == other.name &&
          summary == other.summary &&
          picturePath == other.picturePath;
}

class PersonSnapshot {
  final PlatformInt64 tmdbId;
  final String name;
  final String character;
  final String jobName;
  final String picturePath;

  const PersonSnapshot({
    required this.tmdbId,
    required this.name,
    required this.character,
    required this.jobName,
    required this.picturePath,
  });

  @override
  int get hashCode =>
      tmdbId.hashCode ^
      name.hashCode ^
      character.hashCode ^
      jobName.hashCode ^
      picturePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonSnapshot &&
          runtimeType == other.runtimeType &&
          tmdbId == other.tmdbId &&
          name == other.name &&
          character == other.character &&
          jobName == other.jobName &&
          picturePath == other.picturePath;
}
