// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PersonData {
  final PlatformInt64 extId;
  final String name;
  final String biography;
  final String? pictureApiPath;
  final String pictureFilePath;

  const PersonData({
    required this.extId,
    required this.name,
    required this.biography,
    this.pictureApiPath,
    required this.pictureFilePath,
  });

  @override
  int get hashCode =>
      extId.hashCode ^
      name.hashCode ^
      biography.hashCode ^
      pictureApiPath.hashCode ^
      pictureFilePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonData &&
          runtimeType == other.runtimeType &&
          extId == other.extId &&
          name == other.name &&
          biography == other.biography &&
          pictureApiPath == other.pictureApiPath &&
          pictureFilePath == other.pictureFilePath;
}
