// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../movie_data/movie_data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_tracing_subscriber`

Future<String> start({
  required String path,
  required String username,
  required String password,
  required String token,
}) => RustLib.instance.api.crateApiMediaStart(
  path: path,
  username: username,
  password: password,
  token: token,
);

Future<List<MovieSnapshot>> getMedia({required String mediaType}) =>
    RustLib.instance.api.crateApiMediaGetMedia(mediaType: mediaType);
